Use backtrace debugging with UNO R4 WiFi [HC-1341]
arduino/help-center-content pull request #265
Opened 2023-09-11 11:59 UTC by seaxwi

2023-09-13 09:12 UTC, Renat0Ribeir0 requested changes

2023-09-13 09:12 UTC, Renat0Ribeir0 commented on content/Hardware Support/UNO/Use-stack-backtrace-to-debug-a-sketch-for-UNO-R4-WiFi.md
> +5. **Windows only:** Paste the command in a text editor. Replace "C:" with "/mnt/c" and replace **all** backslashes (\\) with forward slashes (/).
```suggestion
3. **Windows only:** Paste the command in a text editor. Replace "C:" with "/mnt/c" and replace **all** backslashes (\\) with forward slashes (/).
4. Open Terminal (macOS, Linux) or [Windows Powershell](https://learn.microsoft.com/en-us/powershell/scripting/windows-powershell/starting-windows-powershell?view=powershell-7.3).
   * **Windows only:** Type `Ubuntu` into Windows Powershell and press <kbd>Enter</kbd>.
5. Paste the `addr2line` command (or the `addr2line` command altered in step 3, if using **Windows**) and press <kbd>Enter</kbd>.
```
Is altering the addr2line command in a text editor necessary before pasting it into the Powershell? If so, I would consider restructuring the list in this order.

2023-09-13 09:12 UTC, Renat0Ribeir0 commented on content/Hardware Support/UNO/Use-stack-backtrace-to-debug-a-sketch-for-UNO-R4-WiFi.md
> +Follow these steps to run the addr2line command:
```suggestion
Follow these steps to run the `addr2line` command:
```
Formatting

2023-09-19 09:13 UTC, Renat0Ribeir0 approved these changes
LGTM 👍

2023-09-21 10:07 UTC, seaxwi commented
@Renat0Ribeir0 Made some small additional changes, could you have a look?

2023-09-21 11:53 UTC, Renat0Ribeir0 approved these changes

2023-09-22 08:48 UTC, merged