Use Arduino Create Agent with Brave Browser [HC-1281]
arduino/help-center-content pull request #266
Opened 2023-09-12 14:54 UTC by Renat0Ribeir0

Adds an article documenting how allow communication between Brave Browser and Arduino Create Agent.

2023-09-18 09:26 UTC, seaxwi requested changes

2023-09-19 08:46 UTC, Renat0Ribeir0 commented on content/Arduino Cloud/Web Editor/Use-Arduino-Create-Agent-with-Brave-Browser.md
> +* `"To upload a sketch via USB port, make sure the Agent is installed and running on this computer"`
Good point!

2023-09-19 08:50 UTC, Renat0Ribeir0 commented
Thanks for the review. I will wait with linking to from the other related articles until the improvement (HC-1376) is done.

2023-09-19 09:08 UTC, seaxwi approved these changes
LGTM 👍

2023-09-19 09:15 UTC, merged