Opta FAQ collection [HC-1523]
arduino/help-center-content pull request #360
Opened 2024-04-24 14:02 UTC by gorillagripcore

2024-05-03 09:58 UTC, seaxwi requested changes

2024-05-03 09:58 UTC, seaxwi commented on content/Hardware Support/Portenta Family/Opta-FAQ.md
> +## FAQ
```suggestion
---
```

2024-05-03 09:58 UTC, seaxwi commented on content/Hardware Support/Portenta Family/Opta-FAQ.md
> +The frequently asked questions covered in this article are focused on providing essential information about The Arduino Opta® and how to operate it with ease.
```suggestion
The frequently asked questions covered in this article are focused on providing essential information about Arduino Opta® and how to operate it with ease.
```

2024-05-03 14:53 UTC, i-herrera approved these changes
Looks good to me!

2024-05-06 08:08 UTC, seaxwi requested changes

2024-05-06 08:08 UTC, seaxwi commented on content/Hardware Support/Portenta Family/FAQ-Arduino-Opta.md
> +Yes, the reliability data is provided under MIL-HDBK-217F standards and component information. Opta® Lite and Opta® RS485 have MTBF (Mean Time Between Failures) of 87 years (766,000 h) at 25 °C. They
Can you format this as a list?

2024-05-06 15:20 UTC, seaxwi approved these changes

2024-05-07 06:59 UTC, merged