Import an Arduino Cloud Template [HC-1574]
arduino/help-center-content pull request #389
Opened 2024-07-04 06:23 UTC by gorillagripcore

2024-07-04 14:06 UTC, Renat0Ribeir0 requested changes

2024-07-04 14:06 UTC, Renat0Ribeir0 commented on content/Arduino Cloud/General Cloud/Import-an-Arduino-Cloud-Template.md
> +    ![Dialog box for entering network credentials](img/Set_network_parameters.png)
```suggestion
    ![Dialog box for entering network credentials](img/Set_network_parameters.png)
    
---
    
## Still need help?

* [If you can't import a template in Arduino Cloud](https://support.arduino.cc/hc/en-us/articles/4408887422994-If-you-can-t-import-a-template-in-Arduino-Cloud)
* [If your device can't be added to Arduino Cloud](https://support.arduino.cc/hc/en-us/articles/360019355679-If-your-device-can-t-be-added-to-Arduino-Cloud)
```
Added section with links to troubleshooting articles relevant during the process

2024-07-04 15:13 UTC, Renat0Ribeir0 approved these changes

2024-07-08 08:27 UTC, seaxwi approved these changes
@gorillagripcore Left one suggestion, LGTM otherwise!

2024-07-08 08:27 UTC, seaxwi commented on content/Arduino Cloud/General Cloud/Import-an-Arduino-Cloud-Template.md
> +## Still need help?
The "Still need help?" heading should be used to provide additional solutions in articles that are already framed as troubleshooting. Example: ['Error: avrdude' when uploading](https://github.com/arduino/help-center-content/blob/98d433d448b693a5128f0dfd900d0013ebc1b769/content/Software%20Support/Upload/Error-avrdude-when-uploading.md?plain=1#L220-L231)

For "how to" articles, such as this one, use either "Troubleshooting" (general purpose) or a troubleshooting style title "If.. [issue]" (more specific).

```suggestion
## Troubleshooting
```

2024-07-08 08:32 UTC, merged