Improvements to "Use PWM with Arduino" [HC-HC-1483]
arduino/help-center-content pull request #411
Opened 2024-09-09 09:24 UTC by gorillagripcore

check comment in Jira 🙃

2024-09-16 10:24 UTC, Renat0Ribeir0 requested changes

2024-09-16 10:24 UTC, Renat0Ribeir0 commented on content/Hardware Support/Generic/Use-PWM-output-with-Arduino.md
> +```
```suggestion
To change the resolution, use `analogWriteResolution(bits)`, where `bits` determines the resolution in bits, ranging from 1 to 32. [See an example code](https://docs.arduino.cc/language-reference/en/functions/analog-io/analogWriteResolution/#example-code).
```
I suggest linking directly to the example in the documentation.

2024-09-16 10:24 UTC, Renat0Ribeir0 commented on content/Hardware Support/Generic/Use-PWM-output-with-Arduino.md
> +
```suggestion

> [!NOTE]
> If the resolution set is higher than your board’s capabilities, the extra bits will be discarded. If it's lower than your board’s capabilities, the missing bits will be padded with zeros.

```
This information can be displayed as a note.

2024-09-16 12:46 UTC, Renat0Ribeir0 approved these changes
LGTM 👍

2024-09-23 08:57 UTC, seaxwi approved these changes

2024-09-24 13:17 UTC, merged