Improvements to "Review, change, or cancel an Arduino Cloud plan" [HC-1184]
arduino/help-center-content pull request #437
Opened 2024-10-16 12:22 UTC by Renat0Ribeir0

2024-10-18 02:16 UTC, Kristof-nRf requested changes

2024-10-18 02:16 UTC, Kristof-nRf commented on content/Arduino Cloud/General Cloud/Review-change-or-cancel-an-Arduino-Cloud-plan.md
>  * [Modify a plan](#switch)
PINID

2024-10-21 12:55 UTC, seaxwi commented on content/Arduino Cloud/General Cloud/Review-change-or-cancel-an-Arduino-Cloud-plan.md
>  You can review, change or cancel your Arduino Cloud plan at any time:
```suggestion
You can review, change or cancel your Arduino Cloud plan at any time.

In this article:
```

2024-10-21 12:56 UTC, seaxwi commented
One suggestion, LGTM

2024-10-21 15:05 UTC, merged