Improvements to "Reset the Arduino bootloader on the Nano ESP32" [HC-1612]
arduino/help-center-content pull request #445
Opened 2024-11-04 11:30 UTC by seaxwi

Document bootloader mode option and clarify some steps based on article feedback

2024-11-05 10:32 UTC, Renat0Ribeir0 requested changes
Looks good! Left some minor suggestions. Also, since it is mentioned that this process works in Arduino IDE and Cloud Editor (_"3. Select Arduino Nano ESP32 in Arduino IDE or the Cloud Editor."_), the intro should be updated.

2024-11-05 10:32 UTC, Renat0Ribeir0 commented on content/Hardware Support/Nano Family/Reset-the-Arduino-bootloader-on-the-Nano-ESP32.md
> +* Ensure that the **Esptool** option is selected in the Sketch > Upload Using Programmer menu. It needs to be actively selected, even if no other options are available. You will know the Esptool opti
```suggestion
* Ensure that the **Esptool** option is selected in the **Sketch > Upload Using Programmer** menu. It needs to be actively selected, even if no other options are available. You will know the Esptool option is selected if a checkmark is displayed next to the name.
```

2024-11-05 10:32 UTC, Renat0Ribeir0 commented on content/Hardware Support/Nano Family/Reset-the-Arduino-bootloader-on-the-Nano-ESP32.md
> +8. Click on and the **Esptool** option to select it.
```suggestion
8. Click on the **Esptool** option to select it.
```
Typo

2024-11-06 10:35 UTC, seaxwi commented
> since it is mentioned that this process works in Arduino IDE and Cloud Editor (_"3. Select Arduino Nano ESP32 in Arduino IDE or the Cloud Editor."_), the intro should be updated.

@Renat0Ribeir0 Good point! Programmer selection is not available in the Cloud Editor, but that's only needed for the option 2. I have made some adjustmens in e568360e980ffbcb632cc38096186c9cc09476c0

2024-11-06 10:49 UTC, Renat0Ribeir0 approved these changes

2024-11-06 13:12 UTC, merged