Community translations now available in IDE 2
arduino/help-center-content pull request #58
Opened 2022-04-27 08:25 UTC by seaxwi

**Changes proposed in this pull request**
Add troubleshooting and temporary note about update adding community translations.

**Internal key:** HC-979

**Please check**
- [ ] This pull request changes an article title
- [ ] This pull request removes an article

2022-04-27 08:40 UTC, per1234 requested changes

2022-04-27 08:40 UTC, per1234 commented on content/Software and Downloads/IDE Settings/Change-the-language-in-Arduino-IDE.md
> +> **Note:** Commnunity translations were added to Arduino IDE 2.0 in version **2.0.0-rc6**. You can find the latest version on the [Software page](https://www.arduino.cc/en/software).. <!-- TEMP_NOTI
```suggestion
> **Note:** Community translations were added to Arduino IDE 2.0 in version **2.0.0-rc6**. You can find the latest version on the [Software page](https://www.arduino.cc/en/software).. <!-- TEMP_NOTICE: 22-04-27 -->
```

2022-04-29 14:17 UTC, Renat0Ribeir0 requested changes

2022-05-03 11:55 UTC, seaxwi commented on content/Software and Downloads/IDE Settings/Change-the-language-in-Arduino-IDE.md
> +> **Note:** Commnunity translations were added to Arduino IDE 2.0 in version **2.0.0-rc6**. You can find the latest version on the [Software page](https://www.arduino.cc/en/software).. <!-- TEMP_NOTI
Fixed! 8961d8c

2022-05-03 12:46 UTC, Renat0Ribeir0 approved these changes
LGTM 👍

2022-05-03 13:43 UTC, merged